api_platform:


  defaults:
    pagination_enabled: false
    pagination_items_per_page: 5
    pagination_client_enabled: true
    pagination_client_items_per_page: true


  collection:
    pagination:
      items_per_page_parameter_name: 'count'

